include:
  - cumulus.license
  - cumulus.static
  - cumulus.layer3interfaces
  - cumulus.frr
  - cumulus.layer2interfaces
  - cumulus.edge_filters
  - cumulus.lldpd
  - cumulus.sflow
  - cumulus.snmpd
  - cumulus.fdb
